# Generated by Django 3.0.6 on 2020-05-04 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
