# Generated by Django 3.0.6 on 2020-05-05 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadfiles_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
