# Generated by Django 3.0.6 on 2020-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_uploadfiles_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='fileL',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
