# Generated by Django 3.0.6 on 2020-06-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_uploadfiles_filel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='uid',
        ),
    ]
